# SPDX-FileCopyrightText: 2025 rstared contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "rstared"
version = "0.8.3"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Simple decorator that adds rstar::RTree to collections such as HashMap, BTreeMap, StableVec, thunderdome::Arena."
repository = "https://codeberg.org/topola/rstared"
documentation = "https://docs.rs/rstared"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["rtree", "no_std"]
categories = ["data-structures", "game-development", "gui", "no-std", "rust-patterns"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["std", "rstar", "maplike/rstar"]
std = []
rstar = []
stable-vec = ["dep:stable-vec", "maplike/stable-vec"]
thunderdome = ["dep:thunderdome", "maplike/thunderdome"]

[dependencies]
maplike = { version = "0.8", features = ["rstar"] }
rstar = "0.12"
stable-vec = { version = "0.4", optional = true }
thunderdome = { version = "0.6", optional = true }

[dev-dependencies]
rand = "0.9"

[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]

[[example]]
name = "basic_usage"
required-features = ["std"]
doc-scrape-examples = true
