# SPDX-FileCopyrightText: 2025 rstared contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "rstared"
version = "0.15.0"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Simple decorator that adds rstar::RTree to arbitrary collections."
repository = "https://github.com/mikwielgus/rstared"
documentation = "https://docs.rs/rstared"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["rtree", "no_std"]
categories = ["data-structures", "game-development", "gui", "no-std", "rust-patterns"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["std"]
std = ["maplike/std"]
arrayvec = ["maplike/arrayvec"]
bidimap = ["maplike/bidimap"]
geo = ["maplike/geo", "dep:geo-types"]
indexmap = ["maplike/indexmap"]
mint = ["dep:mint"]
serde = ["dep:serde", "smallvec/serde"]
smallvec = ["maplike/smallvec"]
stable-vec = ["maplike/stable-vec"]
thunderdome = ["maplike/thunderdome"]
tinyvec = ["maplike/tinyvec"]
undoredo = ["dep:undoredo"]

[dependencies]
heapless = { version = "0.9", default-features = false }
maplike = { version = "0.15", features = ["alloc"], default-features = false }
numlike = { version = "0.5", default-features = false, features = ["libm"] }
smallvec = "1.6"
geo-types = { version = "0.7", optional = true, default-features = false }
mint = { version = "0.5.9", optional = true }
serde = { version = "1.0", optional = true, default-features = false, features = ["alloc", "derive"] }
undoredo = { version = "0.15", default-features = false, optional = true }

[dev-dependencies]
approx = "0.5"
geo-types = { version = "0.7", default-features = false }
nalgebra = { version = "0.33", default-features = false, features = ["std", "mint"] }
rand = "0.10"
rand_hc = "0.5"
serde_json = "1.0"
stable-vec = "0.4"
thunderdome = "0.6"

# Use scraped examples.
[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "hashmap"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "multipolygon"
required-features = ["geo"]
doc-scrape-examples = true

[[example]]
name = "thunderdome"
required-features = ["thunderdome", "geo"]
doc-scrape-examples = true

[[example]]
name = "undoredo"
required-features = ["undoredo", "std"]
doc-scrape-examples = true

[[example]]
name = "vec"
doc-scrape-examples = true
