# SPDX-FileCopyrightText: 2025 rstared contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "rstared"
version = "0.14.0"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Simple decorator that adds rstar::RTree to arbitrary collections."
repository = "https://github.com/mikwielgus/rstared"
documentation = "https://docs.rs/rstared"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["rtree", "no_std"]
categories = ["data-structures", "game-development", "gui", "no-std", "rust-patterns"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["std"]
std = ["maplike/std"]
arrayvec = ["dep:arrayvec", "maplike/arrayvec"]
bidimap = ["dep:bidimap", "maplike/bidimap"]
indexmap = ["dep:indexmap", "maplike/indexmap"]
smallvec = ["dep:smallvec", "maplike/smallvec"]
stable-vec = ["dep:stable-vec", "maplike/stable-vec"]
thunderdome = ["dep:thunderdome", "maplike/thunderdome"]
tinyvec = ["dep:tinyvec", "maplike/tinyvec"]
undoredo = ["dep:undoredo"]

[dependencies]
arrayvec = { version = "0.7", optional = true }
bidimap = { version = "0.7", optional = true }
indexmap = { version = "2.14", optional = true }
maplike = { version = "0.14", features = ["alloc", "rstar"], default-features = false }
rstar = "0.13"
smallvec = { version = "1", optional = true }
stable-vec = { version = "0.4", optional = true }
thunderdome = { version = "0.6", optional = true }
tinyvec = { version = "1", features = ["alloc"], optional = true }
undoredo = { version = "0.14", features = ["rstar"], default-features = false, optional = true }

[dev-dependencies]
rand = "0.9"
stable-vec = "0.4"
thunderdome = "0.6"

# Use scraped examples.
[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "hashmap"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "undoredo"
required-features = ["undoredo", "std"]
doc-scrape-examples = true
