# SPDX-FileCopyrightText: 2026 undoredo contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

shared-version = true
tag-name = "{{version}}"
pre-release-hook = [
  "cargo",
  "semver-checks",
  "check-release",
  "-p",
  "{{crate_name}}",
  "--baseline-version",
  "{{prev_version}}",
]
pre-release-commit-message = "Release version {{version}}"
pre-release-replacements = [
  { file = "README.md", search = 'rstared = \{ version = "[^"]+"([^}]*)\}', replace = '{{crate_name}} = { version = "{{version}}"$1}' },
]
