# SPDX-FileCopyrightText: 2026 rstared contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

steps:
  check_test_coverage:
    image: rust
    environment:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
    commands:
      - cargo install cargo-llvm-cov
      - cargo llvm-cov --all-features --all-targets --fail-under-lines 60
    when:
      event: [pull_request, push, tag]
